namespace BaanCorner.Services
{
    public static class UnitService
    {
        public static List<string> GetUnitFormats(Units projectUnits, ForgeTypeId spec)
        {
            if (UnitFormats.FormatMapping.TryGetValue(spec, out var availableFormats))
            {
                return availableFormats
                    .Where(s => !string.IsNullOrEmpty(s))
                    .Distinct()
                    .ToList();
            }

            return new List<string>();
        }

        public static string GetSelectedFormat(Units projectUnits, ForgeTypeId spec)
        {
            var formatOption = projectUnits.GetFormatOptions(spec);
            var typeId = formatOption.GetUnitTypeId().TypeId;

            string input = typeId;
            int start = input.IndexOf(":") + 1;
            int end = input.IndexOf("-");

            string result = input.Substring(start, end - start);

            // Mapping Display Text
            return result switch
            {
                "degrees" => "Degrees",
                "radians" => "Radians",
                "gradians" => "Gradians",
                "squareCentimeters" => "Square centimeters",
                "squareInches" => "Square inches",
                "squareMillimeters" => "Square millimeters",
                "squareMeters" => "Square meters",
                "squareFeet" => "Square feet",
                "hectares" => "Hectares",
                "acres" => "Acres",
                "currencyPerSquareFoot" => "Cost per square foot",
                "currencyPerSquareMeter" => "Cost per square meter",
                "centimeters" => "Centimeters", 
                "decimeters" => "Decimeters", 
                "inches" => "Inches", 
                "USSurveyFeet" => "US survey feet",
                "meters" => "Meters",
                "millimeters" => "Millimeters",
                "feet" => "Feet",
                "feetFractionalInches" => "Feet and fractional inches",
                "fractionalInches" => "Fractional inches", 
                "metersCentimeters" => "Meter and centimeters",
                "kilogramsPerCubicMeter" => "Kilograms per cubic meter", 
                "poundsMassPerCubicFoot" => "Pounds mass per cubic foot",
                "pi" => "Number of n",
                "1ToRatio" => "1 : Ratio",
                "perMile" => "Per mile", 
                "percentage" => "Percentage", 
                "ratioTo1" => "Ratio : 1", 
                "ratioTo10" => "Ratio : 10",
                "ratioTo12" => "Ratio : 12",
                "riseDividedBy1000Millimeters" => "Rise / 1000 millimeters", 
                "riseDividedBy10Feet" => "Rise / 10 feet", 
                "riseDividedBy120Inches" => "Rise / 120 inches", 
                "riseDividedBy12Inches" => "Rise / 12 inches", 
                "riseDividedBy1Foot" => "Rise /1 foot", 
                "slopeDegrees" => "Degrees",
                "centimetersPerMinute" => "Centimeters per minute",
                "feetPerMinute" => "Feet per minute",
                "feetPerSecond" => "Feet per second",
                "kilometersPerHour" => "Kilometers per hour",
                "metersPerSecond" => "Meters per second",
                "milesPerHour" => "Miles per hour",
                "hours" => "Hours",
                "milliseconds" => "Milliseconds", 
                "minutes" => "Minutes", 
                "seconds" => "Seconds",
                "cubicCentimeters" => "Cubic centimeters", 
                "cubicFeet" => "Cubic feet", 
                "cubicInches" => "Cubic inches", 
                "cubicMeters" => "Cubic meters", 
                "cubicMillimeters" => "Cubic millimeters", 
                "cubicYards" => "Cubic yards", 
                "liters" => "Liters", 
                "usGallons" => "US gallons",
                "britishThermalUnitsPerHour" => "British thermal units per hour",
                "britishThermalUnitsPerSecond" => "British thermal units per second",
                "caloriesPerSecond" => "Calories per second",
                "horsepower" => "Horsepower",
                "kilocaloriesPerSecond" => "Kilocalories per second",
                "kilovoltAmperes" => "Kilovolt amperes",
                "kilowatts" => "Kilowatts",
                "voltAmperes" => "Volt amperes",
                "watts" => "Watts",
                "voltAmperesPerSquareFoot" => "Volt amperes per square foot",
                "voltAmperesPerSquareMeter" => "Volt amperes per square meter",
                "kelvin" => "Kelvin",
                "currencyPerBritishThermalUnit" => "Cost per British thermal unit",
                "currencyPerWattHour" => "Cost per watt hour",
                "currencyPerBritishThermalUnitPerHour" => "Cost per British thermal unit per hour",
                "currencyPerWatt" => "Cost per watt",
                "amperes" => "Amperes",
                "kiloamperes" => "Kiloamperes",
                "milliamperes" => "Milliamperes",
                "lux" => "Lumens per watt",
                "fixed" => "Fixed",
                "candelasPerSquareFoot" => "Candelas per square foot",
                "candelasPerSquareMeter" => "Candelas per square meter",
                "footlamberts" => "Footlamberts",
                "lumens" => "Lumens",
                "candelas" => "Candelas",
                "kilovolts" => "Kilovolts",
                "millivolts" => "Millivolts",
                "volts" => "Volts",
                "britishThermalUnitsPerHourSquareFoot" => "British thermal units per hour square foot",
                "wattsPerSquareFoot" => "Watts per square foot",
                "wattsPerSquareMeter" => "Watts per square meter",
                "wattsPerFoot" => "Watts per foot",
                "wattsPerMeter" => "Watts per meter",
                "ohmMeters" => "Ohm meters",
                "celsius" => "Celsius",
                "fahrenheit" => "Fahrenheit",
                "rankine" => "Rankine",
                "britishThermalUnits" => "British thermal units",
                "calories" => "Calories",
                "joules" => "Joules",
                "kilocalories" => "Kilocalories",
                "kilowattHours" => "Kilowatt hours",
                "therms" => "Therms",
                "poundForceFeet" => "Pound force feet",
                "britishThermalUnitsPerSquareFootDegreeFahrenheit" => "British thermal units per square foot degree Fahrenheit",
                "joulesPerSquareMeterKelvin" => "Joules per square meter Kelvin",
                "kilojoulesPerSquareMeterKelvin" => "Kilojoules per square meter Kelvin",
                "britishThermalUnitsPerHourSquareFootDegreeFahrenheit" => "British thermal units per hour square foot degree Fahrenheit",
                "wattsPerSquareMeterKelvin" => "Watts per square meter kelvin",
                "cubicFeetPerPoundMass" => "Cubic feet per pound mass",
                "cubicMetersPerKilogram" => "Cubic meters per kilogram",
                "grainsPerHourSquareFootInchMercury" => "Grains per hour square foot inch mercury",
                "nanogramsPerPascalSecondSquareMeter" => "Nanograms per pascal second square meter",
                "britishThermalUnitsPerPoundDegreeFahrenheit" => "British thermal units per pound degree Fahrenheit",
                "joulesPerGramDegreeCelsius" => "Joules per gram degree Celsius",
                "joulesPerKilogramDegreeCelsius" => "Joules per kilogram degree Celsius",
                "britishThermalUnitsPerPound" => "British thermal units per pound",
                "joulesPerGram" => "Joules per gram",
                "britishThermalUnitsPerHourFootDegreeFharenheit" => "British thermal units per hour foot degree Fahrenheit",
                "wattsPerMeterKelvin" => "Watts per meter kelvin",
                "kilogramsPerKilogramKelvin" => "Kilograms per kilogram kelvin",
                "poundsMassPerPoundDegreeFahrenheit" => "Kilograms per kilogram kelvin",
                "britishThermalUnitsPerDegreeFahrenheit" => "British thermal units per degree Fahrenheit",
                "joulesPerKelvin" => "Joules per Kelvin",
                "kilojoulesPerKelvin" => "Kilojoules per Kelvin",
                "hourSquareFootDegreesFahrenheitPerBritishThermalUnit" => "Hour square foot degrees Fahrenheit per British thermal unit",
                "squareMeterKelvinsPerWatt" => "Square meter kelvins per watt",
                "cubicFeetPerHour" => "Cubic feet per hour",
                "cubicFeetPerMinute" => "Cubic feet per minute",
                "cubicMetersPerHour" => "Cubic meters per hour",
                "cubicMetersPerSecond" => "Cubic meters per second",
                "cubicFeetPerMinuteCubicFoot" => "Cubic feet per minute cubic foot",
                "cubicFeetPerHourCubicMeter" => "Cubic meters per hour cubic meter",
                "litersPerSecondCubicMeter" => "Liters per second cubic meter",
                "litersPerHour" => "Liters per hour",
                "litersPerSecond" => "Liters per second",
                "usGallonsPerHour" => "US gallons per hour",
                "usGallonsPerMinute" => "US gallons per minute",
                "cubicFeetPerMinuteSquareFoot" => "Cubic feet per minute square foot",
                "cubicMetersPerHourSquareMeter" => "Cubic meters per hour square meter",
                "litersPerSecondSquareMeter" => "Liters per second square meter",
                "cubicFeetPerMinuteTonOfRefrigeration" => "Cubic feet per minute ton of refrigeration",
                "litersPerSecondKilowatt" => "Liters per second kilowatt",
                "revolutionsPerMinute" => "Revolutions per minute",
                "revolutionsPerSecond" => "Revolutions per second",
                "squareFeetPerThousandBritishThermalUnitsPerHour" => "Square feet per thousand British thermal units per hour",
                "squareFeetPer1000BritishThermalUnitsPerHour" => "Square feet per thousand British thermal units per hour",
                "squareFeetPerTonOfRefrigeration" => "Square feet per ton of refrigeration",
                "squareMetersPerKilowatt" => "Square meters per kilowatt",
                "tonsOfRefrigeration" => "Tons of refrigeration",
                "britishThermalUnitsPerHourCubicFoot" => "British thermal units per hour cubic foot",
                "wattsPerCubicFoot" => "Watts per cubic foot",
                "wattsPerCubicMeter" => "Watts per cubic meter",
                "poundsMassPerCubicInch" => "Pounds mass per cubic inch",
                "squareFeetPerSecond" => "Square feet per second",
                "squareMetersPerSecond" => "Square meters per second",
                "cubicFeetPerMinutePerBritishThermalUnitPerHour" => "Cubic feet per minute per British thermal unit per hour",
                "cubicMetersPerWattSecond" => "Cubic meters per watt second",
                "feetOfWater39.2DegreesFahrenheitPer100Feet" => "Feet of water (39.2 \u00b0F) per 100 feet",
                "inchesOfWater60DegreesFahrenheitPer100Feet" => "Inches of water (60 \u00b0F) per 100 feet",
                "inchesOfWater60DegreesFahrenheit" => "Inches of water (60 \u00b0F)",
                "metersOfWaterColumnPerMeter" => "Meters of water column per meter",
                "millimetersOfWaterColumnPerMeter" => "Millimeters of water column per meter",
                "pascalsPerMeter" => "Pascals per meter",
                "kilogramsPerHour" => "Kilograms per hour",
                "kilogramsPerMinute" => "Kilograms per minute",
                "kilogramsPerSecond" => "Kilograms per second",
                "poundsMassPerHour" => "Pounds mass per hour",
                "poundsMassPerMinute" => "Pounds mass per minute",
                "poundsMassPerSecond" => "Pounds mass per second",
                "wattsPerCubicFootPerMinute" => "Watts per cubic foot per minute",
                "wattsPerCubicMeterPerSecond" => "Watts per cubic meter per second",
                "atmospheres" => "Atmospheres",
                "bars" => "Bars",
                "kilopascals" => "Kilopascals",
                "megapascals" => "Megapascals",
                "metersOfWaterColumn" => "Meters of water column",
                "millimetersOfMercury" => "Millimeters of mercury",
                "millimetersOfWaterColumn" => "Millimeters of water column",
                "pascals" => "Pascals",
                "poundsForcePerSquareInch" => "Pounds force per square inch",
                "feetOfWater39.2DegreesFahrenheit" => "Feet of water (39.2 \u00b0F)",
                "inchesOfMercury32DegreeFahrenheit" => "Inches of mercury (32 \u00b0F)",
                "inchesOfWater60DegreeFahrenheit" => "Inches of water (60 \u00b0F)",
                /*
                 * Infrastructure
                 */
                "stationingFeet" => "Feet",
                "stationingMeters" => "Meters",
                "stationingSurveyFeet" => "US survey feet",
                
                /*
                 * Piping
                 */
                "centipoises" => "Centipoises",
                "kilogramsPerMeterHour" => "Kilograms per meter hour",
                "kilogramsPerMeterSecond" => "Kilograms per meter second",
                "newtonSecondPerSquareMeter" => "Newton seconds per square meter",
                "pascalSecond" => "Pascal seconds",
                "poundForceSecondPerSquareFoot" => "Pound force seconds per square foot",
                "poundMassPerFootHour" => "Pound mass per foot hour",
                "poundMassPerFootSecond" => "Pounds mass per foot second",
                
                /*
                 * Structural
                 */
                "feetPerSecondSquared" => "Feet per second squared",
                "inchesPerSecondSquared" => "Inches per second squared",
                "kilometersPerSecondSquared" => "Kilometers per second squared",
                "metersPerSecondSquared" => "Meters per second squared",
                "milesPerSecondSquared" => "Miles per second squared",
                "dekanewtonsPerSquareMeter" => "Dekanewtons per square meter",
                "kilogramsForcePerSquareMeter" => "Kilograms force per square meter",
                "kilonewtonsPerSquareMeter" => "Kilonewtons per square meter",
                "kipsPerSquareFoot" => "Kips per square foot",
                "kipsPerSquareInch" => "Kips per square inch",
                "meganewtonsPerSquareMeter" => "Meganewtons per square meter",
                "newtonsPerSquareMeter" => "Newtons per Square meter",
                "poundsForcePerSquareFoot" => "Pounds force per square foot",
                "tonnesForcePerSquareMeter" => "Tonnes force per square meter",
                "poundsForcePerCubicFoot" => "Pounds force per cubic foot",
                "kilogramForceMeters" => "Kilogram force meters",
                "kilojoules" => "Kilojoules",
                "newtonMeters" => "Newton meters",
                "cyclePerSecond" => "Cycles per second",
                "hertz" => "Hertz",
                "kilonewtonsPerSquareCentimeter" => "Kilonewtons per square centimeter",
                "kilonewtonsPerSquareMillimeter" => "Kilonewtons per square millimeter",
                "newtonsPerSquareMillimeter" => "Newtons per square millimeter",
                "dekanewtonsPerMeter" => "Dekanewtons per meter",
                "kilogramForcePerMeter" => "Kilogram force per meter",
                "kilogramForcePerSquareMeter" => "Kilogram force per square meter",
                "kipsPerFoot" => "Kips per foot",
                "kipsPerInch" => "Kips per inch",
                "meganewtonsPerMeter" => "Meganewtons per meter",
                "newtonsPerMeter" => "Newtons per meter",
                "poundsForcePerFoot" => "Pounds force per foot",
                "tonnesForcePerMeter" => "Tonnes force per meter",
                "dekanewtonMetersPerMeter" => "Dekanewton meters per meter",
                "kilogramForceMetersPerMeter" => "Kilogram force meters per meter",
                "kilonewtonMetersPerMeter" => "Kilonewton meters per meter",
                "kipFeetPerFoot" => "Kip feet per foot",
                "meganewtonMetersPerMeter" => "Meganewton meters per meter",
                "newtonMetersPerMeter" => "Newton meters per meter",
                "poundForceFeetPerFoot" => "Pound force feet per foot",
                "tonneForceMetersPerMeter" => "Tonne force meters per meter",
                "kilograms" => "Kilograms",
                "poundsMass" => "Pounds mass",
                "tonnes" => "Tonnes",
                "usTonnesMass" => "US tonnes mass",
                "kilogramsPerSquareMeter" => "Kilograms per square meter",
                "poundsMassPerSquareFoot" => "Pounds per square foot",
                "kilogramsPerMeter" => "Kilograms per meter",
                "poundsMassPerFoot" => "Pounds mass per foot",
                "dekanewtonMeters" => "Dekanewton meters",
                "kilonewtonMeters" => "kilonewton meters",
                "kipFeet" => "Kip feet",
                "meganewtonMeters" => "Meganewton meters",
                "tonneForceMeters" => "Tonne force meters",
                "centimetersToTheFourthPower" => "Centimeters to the fourth power",
                "feetToTheFourthPower" => "Feet to the fourth power",
                "inchesToTheFourthPower" => "Inches to the fourth power",
                "metersToTheFourthPower" => "Meters to the fourth power",
                "millimetersToTheFourthPower" => "Millimeters to the fourth power",
                "radiansPerSecond" => "Radians per second",
                "squareCentimetersPerMeter" => "Square centimeters per meter",
                "squareFeetPerFoot" => "Square feet per foot",
                "squareInchesPerFoot" => "Square inches per foot",
                "squareMetersPerMeter" => "Square meters per meter",
                "squareMillimeterPerMeter" => "Square millimeters per meter",
                "kilonewtonMetersPerDegreePerMeter" => "Kilonewton meters per degree per meter",
                "kipFeetPerDegreePerFoot" => "Kip feet per degree per foot",
                "kilonewtonMetersPerDegree" => "Kilonewton meters per degree",
                "kipFeetPerDegree" => "Kip feet per degree","inverseDegreesCelsius" => "Inverse degrees Celsius",
                "inverseDegreesFahrenheit" => "Inverse degrees Fahrenheit",
                "microinchesPerInchDegreeFahrenheit" => "Microinches per inch degree Fahrenheit",
                "micrometersPerMeterDegreeCelsius" => "Micrometers per meter degree Celsius",
                "kilonewtonsPerCubicMeter" => "Kilonewtons per cubic meter",
                "kipsPerCubicInch" => "Kips per cubic inch",
                "centimetersToTheSixthPower" => "Centimeters to the sixth power",
                "feetToTheSixthPower" => "Feet to the sixth power",
                "inchesToTheSixthPower" => "Inches to the sixth power",
                "metersToTheSixthPower" => "Meters to the sixth power",
                "millimetersToTheSixthPower" => "Millimeters to the sixth power",
                "dekanewtons" => "Dekanewtons",
                "kilogramsForce" => "Kilograms force",
                "kilonewtons" => "Kilonewtons",
                "kips" => "Kips",
                "meganewtons" => "Meganewtons",
                "newtons" => "Newtons",
                "poundsForce" => "Pounds force",
                "tonnesForce" => "Tonnes force",
                "usTonnesForce" => "US tonnes force",
                "kipsPerCubicFoot" => "Kips per cubic foot",

                _ => "Unknown"
                
                
            };
        }
    }
}